CREATE DATABASE FOODMAPSERVER
GO

USE FOODMAPSERVER
GO

CREATE TABLE ACCOUNT
(
	USERNAME VARCHAR(20) PRIMARY KEY,
	PASSWORD VARCHAR(20),
	NAME NVARCHAR(40),
	PHONE_NUMBER VARCHAR(11),
	EMAIL VARCHAR(20) UNIQUE
)
GO

CREATE TABLE GUESTACCOUNT
(
	EMAIL VARCHAR(30) PRIMARY KEY,
	NAME NVARCHAR(40)
)
GO

CREATE TABLE DINER
(
	ID INT IDENTITY PRIMARY KEY,
	ID_USER VARCHAR(20),
	NAME NVARCHAR(100) NOT NULL,
	ADDRESS NVARCHAR(50) NOT NULL,
	PHONE_NUMBER VARCHAR(11),
	DESCRIBE TEXT,
	URL_IMAGE NVARCHAR(200), -- LINK IMAGE
	TIMEOPEN TIME NOT NULL,
	TIMECLOSE TIME NOT NULL
)
GO

CREATE TABLE LOCATION
(
	ID_DINER INT NOT NULL,
	LAT FLOAT NOT NULL, -- latitude
	LON FLOAT NOT NULL,	-- longitude
	PRIMARY KEY(LAT, LON)
)
GO

CREATE TABLE FOODS
(
	NAME NVARCHAR(50) NOT NULL,
	ID_DINNER INT,
	PRICE INT,
	URL_IMAGE NVARCHAR(200), -- LINK IMAGE
	ID_CATALOG INT,
	PRIMARY KEY(NAME, ID_DINNER)
)
GO

CREATE TABLE CATALOGS
(
	ID INT PRIMARY KEY,
	NAME NVARCHAR(30) UNIQUE NOT NULL
)
GO

CREATE TABLE TAGS
(
	ID_DINER INT,
	ID_CATALOG INT,
	PRIMARY KEY(ID_DINER, ID_CATALOG)
)
GO

CREATE TABLE COMMENTS
(
	ID_DINER INT NOT NULL,
	EMAIL_USER VARCHAR(30),
	COMMENT NVARCHAR(200) NOT NULL
)
GO

CREATE TABLE RANK
(
	ID_DINER INT NOT NULL,
	EMAIL_USER VARCHAR(30),
	STAR INT NOT NULL, -- 1 tới 5
	PRIMARY KEY(ID_DINER, EMAIL_USER)
)
GO

-- SET FOREIGN KEY
ALTER TABLE dbo.DINER ADD CONSTRAINT FK_DINER_ACCOUNT FOREIGN KEY(ID_USER) REFERENCES dbo.ACCOUNT(USERNAME)
GO

ALTER TABLE dbo.FOODS ADD CONSTRAINT FK_FOODS_DINER FOREIGN KEY(ID_DINNER) REFERENCES dbo.DINER(ID)
GO

ALTER TABLE dbo.FOODS ADD CONSTRAINT FK_FOODS_CATALOGS FOREIGN KEY(ID_CATALOG) REFERENCES dbo.CATALOGS(ID)
GO

ALTER TABLE dbo.TAGS ADD CONSTRAINT FK_TAGS_DINER FOREIGN KEY(ID_DINER) REFERENCES dbo.DINER(ID)
GO

ALTER TABLE dbo.TAGS ADD CONSTRAINT FK_TAGS_CATALOGS FOREIGN KEY(ID_CATALOG) REFERENCES dbo.CATALOGS(ID)
GO

ALTER TABLE dbo.COMMENTS ADD CONSTRAINT FK_COMMENTS_DINER FOREIGN KEY(ID_DINER) REFERENCES dbo.DINER(ID)
GO

ALTER TABLE dbo.COMMENTS ADD CONSTRAINT FK_COMMENTS_GUESTACCOUNT FOREIGN KEY(EMAIL_USER) REFERENCES dbo.GUESTACCOUNT(EMAIL)
GO

ALTER TABLE dbo.RANK ADD CONSTRAINT FK_RANK_DINER FOREIGN KEY(ID_DINER) REFERENCES dbo.DINER(ID)
GO

ALTER TABLE dbo.RANK ADD CONSTRAINT FK_RANK_GUESTACCOUNT FOREIGN KEY(EMAIL_USER) REFERENCES dbo.GUESTACCOUNT(EMAIL)
GO

ALTER TABLE dbo.LOCATION ADD CONSTRAINT FK_LOCATION_DINER FOREIGN KEY(ID_DINER) REFERENCES dbo.DINER(ID)
GO

-- SET RULES
ALTER TABLE dbo.ACCOUNT ADD CONSTRAINT C_ACCOUNT_PHONENUMBER CHECK(LEN(PHONE_NUMBER) IN (10,11))
GO

ALTER TABLE dbo.DINER ADD CONSTRAINT C_DINER_PHONENUMBER CHECK(LEN(PHONE_NUMBER) IN (10,11))
GO

ALTER TABLE dbo.RANK ADD CONSTRAINT C_RANK_STAR CHECK(STAR >= 1 AND STAR <= 5)
GO